// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coqzvcsmwhdafhvrudym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvcXp2Y3Ntd2hkYWZodnJ1ZHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODg3NzYsImV4cCI6MjA2ODA2NDc3Nn0.MUWmrZ6OwWPGcXLFd1il8HgX4y06-gKI3POFuVP-nXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});